### ISSUE TITLE
Info: Version supports

### ISSUE THREAD

**Issue by RameshByndoor** [ismailsimsek/iceberg-examples#1]
I have tried these examples:
1. Iceberg SCD2 throws java.lang.UnsupportedOperationException: MERGE INTO TABLE is not supported temporarily.
2. On trying IcebergAPIdeleteAppend i see "cannot write delete files in a v1 table"
3. On trying IcebergHaoopTables throws "cannot initialize catalog, missing no-arg constructor: org.apache.hive.HiveCatalog"
Can you help clarify is this same at your end.?

**Comment by RameshByndoor** [comment]
3. On trying IcebergHaoopTables throws "cannot initialize catalog, missing no-arg constructor: org.apache.hive.HiveCatalog"
Can you help clarify is this same at your end.?
--this is resolved

**Comment by ismailsimsek** [comment]
Hi @RameshByndoor sorry for the delay 
all 3 examples are working now, also added new example `IcebergJavaApiUpsert`

**Comment by RameshByndoor** [comment]
@ismailsimsek thanks for your reply, I will try and let you know.
